### PR TITLE
Add usage example to the README

### PR DESCRIPTION
**Pull request by koczkatamas**
I did not find any good copy-paste code how to use the library, and I think the code on the homepage is incorrect (in this code `var g = new Gif(someArrayBuffer);` the `Gif` constructor actually expects `KaitaiStream`, not `someArrayBuffer`), and this repo's README is what Google find first for searches like "Kaitai Javascript", so I thought it would be a good place to put this example.

### CODE REVIEW

**Comment by GreyCat** [comment]
Um, not really. Actually, these should go into [JavaScript notes](https://github.com/kaitai-io/kaitai_struct_doc/blob/master/lang_javascript.adoc) — at least they're visible on docs site.

Also, yeah, we definitely need to fix kaitai.io :(

**Comment by koczkatamas** [comment]
Okay, so currently I found code examples on the following pages, I presume we should fix them here:
 - https://github.com/kaitai-io/kaitai_struct#in-javascript
 - http://kaitai.io/#example-java

I agree that we should put the example into the language-specific notes as you mentioned that is visible from the docs site.

But we should make it clear, it's not just "notes" but usage examples too, because I would expect to find such an example somewhere as near to the main page / repo root / etc as I can (IMHO kaitai_struct repo is OK, but in the kaitai_struct_javascript_runtime repo and on doc.kaitai.io this topic needs more visibility). As these are not just notes, they can be _really_ helpful and time-saving examples for newbies IMHO. The notes seems to be "more advanced" topics, only to be read later.

Other problem: for JS I think we need at least a HTML and a Node.js example. But I presume 
 - we want to keep kaitai.io as clean as we can, so we should just fix the 3-line example?
 - but we can add all the usage patterns (Node + browser) to language-specific notes?
 - we can at least mention the lang. specific page as a link after the JS example on https://github.com/kaitai-io/kaitai_struct#in-javascript, right?

Or should we just put these into the main user-guide and link to that from every mentioned place? (Basically add a new chapter / extend chapter 3 with a "quick usage" guide?)

**Comment by GreyCat** [comment]
> https://github.com/kaitai-io/kaitai_struct#in-javascript

I believe we need to remove most of contents from that README and just point people at proper homepage at http://kaitai.io/. They serve exactly the same purpose, and we won't want to maintain both.

> http://kaitai.io/#example-java

Probably you mean http://kaitai.io/#example-javascript, or we have a bug here with IDs as well?

> But we should make it clear, it's not just "notes" but usage examples too, because I would expect to find such an example somewhere as near to the main page / repo root / etc

Sure. Let's think of how we can increase their visibility. For starters, I would suggest putting per-language links to these "notes" from these examples in the homepage?

> we want to keep kaitai.io as clean as we can, so we should just fix the 3-line example?

Yeah, I think so. node.js is actually not the only thing we need to support, probably some other JS engines/stdlibs as well?

> Or should we just put these into the main user-guide and link to that from every mentioned place? (Basically add a new chapter / extend chapter 3 with a "quick usage" guide?)

Chapter 3 needs to be written from the ground up, actually, explaining this whole compile ksy to target lang -> link result into your project -> use workflow, and, *maybe* exploring per-language options. Probably I would stick to very basic per-language usage example and that's it for the user guide. Per-language discussion easily turns into pretty large body of text, so that was the main rationale into extracting per-language notes into distinct documents — so people who want only JS, for example, don't have to dig through tons of other languages.

Also, I've noticed that we don't have ["Usage" boilerplate text for JS](http://formats.kaitai.io/cpio_old_le/javascript.html) — as [we have for C++, for example](http://formats.kaitai.io/cpio_old_le/cpp_stl.html) — would you care to write one? It needs to be pushed as [_build/usage_javascript.html.erb](https://github.com/kaitai-io/kaitai_struct_formats/blob/master/_build/usage_javascript.html.erb), akin to [_build/usage_java.html.erb](https://github.com/kaitai-io/kaitai_struct_formats/blob/master/_build/usage_java.html.erb).

**Comment by koczkatamas** [comment]
The following changes were done instead of this PR:
 - https://github.com/kaitai-io/kaitai_struct/commit/8460728be40139aec2cf32fda75ffc19abde8822
 - https://github.com/kaitai-io/kaitai-io.github.io/pull/5/commits/0fdfbdc82af7af7eb0520e5195e0822903e3ca34
 - https://github.com/kaitai-io/kaitai_struct_formats/commit/92875255ba4dbae1350a0198629ddf825d0a11dc + https://github.com/kaitai-io/kaitai_struct_formats/commit/833971c1a7f95f77e5bd4a9c8ef8a89d133cba6b + https://github.com/kaitai-io/kaitai_struct_formats/commit/97d353d6588546c2d0160857b236a82ee3359014
 - https://github.com/kaitai-io/kaitai_struct_doc/commit/8fd4790dace98565e255417e1496fde9f422e553
 - https://github.com/kaitai-io/kaitai_struct_javascript_runtime/commit/2d36e5cdc129878c873758e6d57f74c2cb4825ab

So I close this PR now.

> Probably you mean http://kaitai.io/#example-javascript, or we have a bug here with IDs as well?

Well, yeah I meant `#example-javascript` but that would not scroll the page because only the Java example is visible by default, so that's why I used `#example-java`.

**Pull request closed without merging**
